version: 2.1

executors:
  docker-docker:
    docker:
      - image: cimg/base:current
    resource_class: small
    
  docker-machine:
    machine:
      image: ubuntu-2204:current
    resource_class: large

commands:
  setup-qemu:
    steps:
      - run:
          name: Setup Qemu
          command: |
            docker run --privileged --rm tonistiigi/binfmt --install all
      - run:
          name: Create builder
          command: |
            docker buildx create --name multi-arch-build --bootstrap --use
      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin

jobs:
  build-cache-amd64:
    executor: docker-machine
    environment:
      CACHE_REPO: igorferreir4/buildcaches
      CACHE_TAG: ts3audiobot-0.13.0-alpha41-amd64
      CACHE_TAG_OLD: ts3audiobot-0.13.0-alpha41-amd64
    working_directory: ~/project/src/0.13.0-alpha41
    steps:
      - checkout:
          path: ~/project
      - setup-qemu
      - run:
          name: Build docker image
          command: |
            docker buildx build \
              --build-arg BUILDKIT_INLINE_CACHE=0 \
              --cache-from="$CACHE_REPO:$CACHE_TAG_OLD" \
              --cache-from="$CACHE_REPO:$CACHE_TAG" \
              --cache-to=type=registry,ref=$CACHE_REPO:$CACHE_TAG,mode=max .

  build-cache-arm64:
    executor: docker-machine
    resource_class: arm.large
    environment:
      CACHE_REPO: igorferreir4/buildcaches
      CACHE_TAG: ts3audiobot-0.13.0-alpha41-arm64
      CACHE_TAG_OLD: ts3audiobot-0.13.0-alpha41-arm64
    working_directory: ~/project/src/0.13.0-alpha41
    steps:
      - checkout:
          path: ~/project
      - setup-qemu
      - run:
          name: Build docker image
          command: |
            docker buildx build \
              --build-arg BUILDKIT_INLINE_CACHE=0 \
              --cache-from="$CACHE_REPO:$CACHE_TAG_OLD" \
              --cache-from="$CACHE_REPO:$CACHE_TAG" \
              --cache-to=type=registry,ref=$CACHE_REPO:$CACHE_TAG,mode=max .

  build-multi-arch:
    executor: docker-machine
    resource_class: large
    environment:
      CACHE_REPO: igorferreir4/buildcaches
      CACHE_AMD64: ts3audiobot-0.13.0-alpha41-amd64
      CACHE_ARM64: ts3audiobot-0.13.0-alpha41-arm64
      IMAGE_REPO: igorferreir4/ts3audiobot
      IMAGE_TAGS: 0.13.0-alpha41,latest
    working_directory: ~/project/src/0.13.0-alpha41
    steps:
      - checkout:
          path: ~/project
      - setup-qemu
      - run:
          name: Build docker image
          command: |
              TAGS=""
              for tag in $(echo $IMAGE_TAGS | tr "," " "); do
                TAGS="$TAGS -t $IMAGE_REPO:$tag"
              done
              docker buildx build \
                  --build-arg BUILDKIT_INLINE_CACHE=0 \
                  --cache-from="$CACHE_REPO:$CACHE_AMD64" \
                  --cache-from="$CACHE_REPO:$CACHE_ARM64" \
                  --push --platform=linux/amd64,linux/arm64/v8 $TAGS .

  deploy:
    executor: docker-docker
    steps:
      # - add_ssh_keys:
      #     fingerprints:
      #       - "SHA256:hLlCCj1OZj3pbBbgrGvfHjdTf20F4IYKyKvyJTMXC/A"
      - run:
          name: Export date of build.
          command: |
            mkdir ~/.ssh
            echo "$SSH_KEY" | base64 --decode >> ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan $SSH_HOST_IGOR_ARM >> ~/.ssh/known_hosts
            ssh $SSH_USER@$SSH_HOST_IGOR_ARM "echo Executado em "$(date -d "-3 hours" +"%d/%m/%G - %Hh:%Mm:%Ss") - ts3audiobot 0.13.0-alpha41" >> circleci-data.txt"
      # - run:
      #     name: Deploy to my server
      #     command: |
      #       ssh $SSH_USER@$SSH_HOST_IGOR_ARM "~/50GB/docker/executar-docker-compose-up-d.sh >> ~/circleci.txt 2>&1"

workflows:
  ts3audiobot-0.13.0-alpha41:
    jobs:
      - build-cache-amd64:
          context: docker-geral

      - build-cache-arm64:
          context: docker-geral

      - build-multi-arch:
          context: docker-geral
          requires:
            - build-cache-amd64
            - build-cache-arm64

      - deploy:
          context: docker-geral
          requires:
            - build-multi-arch